name: Build, test and publish
on: [ push ]

jobs:
  build-test-publish:
    name: Build, test and publish MAUI application
    uses: HavenDV/UpworkPdfGenerator/.github/workflows/maui.yml@master
    with:
      package-name: com.havendv.upworkpdfgenerator
    secrets:
      service-account-json: ${{ secrets.SERVICE_ACCOUNT_JSON }}