name: Build, test and publish
on:
  push:
    branches:
      - master
    tags:
      - v**

jobs:
  build-test-publish:
    name: Build, test and publish MAUI application
    uses: HavenDV/workflows/.github/workflows/maui.yml@main
    with:
      application-name: UpworkPdfGenerator
      package-name: com.havendv.upworkpdfgenerator
      path: src/apps/UpworkPdfGenerator.Apps.Maui
    secrets:
      service-account-json: ${{ secrets.SERVICE_ACCOUNT_JSON }}